"""
Post-GNN analysis pipeline

This script performs:
1. Load gene embeddings generated by GNN
2. Compute gene importance scores
3. Visualize embeddings (PCA)
4. Cluster genes
5. Integrate PRS and cell-type information
6. Identify high-risk gene modules
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA
from sklearn.cluster import KMeans


# ------------------------------------------------
# Load data
# ------------------------------------------------

def load_data():

    emb = pd.read_csv("gene_embeddings.csv")
    gene_prs = pd.read_csv("gene_level_prs.csv")

    print("Embeddings shape:", emb.shape)
    print("PRS shape:", gene_prs.shape)

    return emb, gene_prs


# ------------------------------------------------
# Compute gene importance
# ------------------------------------------------

def compute_gene_importance(emb):

    feature_cols = emb.columns[:-1]

    emb["importance"] = np.linalg.norm(
        emb[feature_cols].values,
        axis=1
    )

    top_genes = emb.sort_values("importance", ascending=False)

    print("\nTop important genes:")
    print(top_genes[["gene", "importance"]].head(20))

    return emb


# ------------------------------------------------
# PCA visualization
# ------------------------------------------------

def visualize_embeddings(emb):

    features = emb.drop(columns=["gene", "importance"], errors="ignore")

    pca = PCA(n_components=2)

    X = pca.fit_transform(features)

    plt.figure(figsize=(8,6))

    plt.scatter(X[:,0], X[:,1], alpha=0.7)

    plt.xlabel("PC1")
    plt.ylabel("PC2")

    plt.title("GNN Gene Embedding Visualization")

    plt.tight_layout()

    plt.show()


# ------------------------------------------------
# Gene clustering
# ------------------------------------------------

def cluster_genes(emb, n_clusters=5):

    features = emb.drop(columns=["gene", "importance"], errors="ignore")

    kmeans = KMeans(n_clusters=n_clusters, random_state=42)

    emb["cluster"] = kmeans.fit_predict(features)

    print("\nCluster distribution:")
    print(emb["cluster"].value_counts())

    return emb


# ------------------------------------------------
# Merge with PRS data
# ------------------------------------------------

def integrate_prs(emb, gene_prs):

    merged = emb.merge(
        gene_prs[["gene", "gene_prs"]],
        on="gene",
        how="left"
    )

    print("\nMerged dataset shape:", merged.shape)

    return merged


# ------------------------------------------------
# Identify high-risk clusters
# ------------------------------------------------

def identify_risk_clusters(merged):

    risk_clusters = merged.groupby("cluster")["gene_prs"].mean()

    print("\nCluster PRS risk scores:")
    print(risk_clusters)

    return risk_clusters


# ------------------------------------------------
# Save results
# ------------------------------------------------

def save_results(merged):

    merged.to_csv("gnn_gene_analysis.csv", index=False)

    print("\nSaved results: gnn_gene_analysis.csv")


# ------------------------------------------------
# Main pipeline
# ------------------------------------------------

def main():

    emb, gene_prs = load_data()

    emb = compute_gene_importance(emb)

    visualize_embeddings(emb)

    emb = cluster_genes(emb)

    merged = integrate_prs(emb, gene_prs)

    identify_risk_clusters(merged)

    save_results(merged)


if __name__ == "__main__":
    main()